[2019-09-22 19:19:55] local.ERROR: Symfony\Component\Console\Exception\RuntimeException: Too many arguments, expected arguments "command" "name". in C:\xampp\htdocs\todolist\vendor\symfony\console\Input\ArgvInput.php:181
Stack trace:
#0 C:\xampp\htdocs\todolist\vendor\symfony\console\Input\ArgvInput.php(88): Symfony\Component\Console\Input\ArgvInput->parseArgument('-')
#1 C:\xampp\htdocs\todolist\vendor\symfony\console\Input\Input.php(62): Symfony\Component\Console\Input\ArgvInput->parse()
#2 C:\xampp\htdocs\todolist\vendor\symfony\console\Command\Command.php(221): Symfony\Component\Console\Input\Input->bind(Object(Symfony\Component\Console\Input\InputDefinition))
#3 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Console\Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 C:\xampp\htdocs\todolist\vendor\symfony\console\Application.php(794): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 C:\xampp\htdocs\todolist\vendor\symfony\console\Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Foundation\Console\ModelMakeCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 C:\xampp\htdocs\todolist\vendor\symfony\console\Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 C:\xampp\htdocs\todolist\artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 {main}  
[2019-09-22 19:21:24] local.ERROR: Symfony\Component\Console\Exception\RuntimeException: The "-r" option does not exist. in C:\xampp\htdocs\todolist\vendor\symfony\console\Input\ArgvInput.php:126
Stack trace:
#0 C:\xampp\htdocs\todolist\vendor\symfony\console\Input\ArgvInput.php(107): Symfony\Component\Console\Input\ArgvInput->parseShortOptionSet('mr')
#1 C:\xampp\htdocs\todolist\vendor\symfony\console\Input\ArgvInput.php(86): Symfony\Component\Console\Input\ArgvInput->parseShortOption('-mr')
#2 C:\xampp\htdocs\todolist\vendor\symfony\console\Input\Input.php(62): Symfony\Component\Console\Input\ArgvInput->parse()
#3 C:\xampp\htdocs\todolist\vendor\symfony\console\Command\Command.php(221): Symfony\Component\Console\Input\Input->bind(Object(Symfony\Component\Console\Input\InputDefinition))
#4 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Console\Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 C:\xampp\htdocs\todolist\vendor\symfony\console\Application.php(794): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 C:\xampp\htdocs\todolist\vendor\symfony\console\Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Foundation\Console\ModelMakeCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 C:\xampp\htdocs\todolist\vendor\symfony\console\Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 C:\xampp\htdocs\todolist\artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 {main}  
[2019-09-22 19:22:10] local.ERROR: Symfony\Component\Console\Exception\RuntimeException: The "--controller" option does not exist. in C:\xampp\htdocs\todolist\vendor\symfony\console\Input\ArgvInput.php:216
Stack trace:
#0 C:\xampp\htdocs\todolist\vendor\symfony\console\Input\ArgvInput.php(152): Symfony\Component\Console\Input\ArgvInput->addLongOption('controller', NULL)
#1 C:\xampp\htdocs\todolist\vendor\symfony\console\Input\ArgvInput.php(84): Symfony\Component\Console\Input\ArgvInput->parseLongOption('--controller')
#2 C:\xampp\htdocs\todolist\vendor\symfony\console\Input\Input.php(62): Symfony\Component\Console\Input\ArgvInput->parse()
#3 C:\xampp\htdocs\todolist\vendor\symfony\console\Command\Command.php(221): Symfony\Component\Console\Input\Input->bind(Object(Symfony\Component\Console\Input\InputDefinition))
#4 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Console\Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 C:\xampp\htdocs\todolist\vendor\symfony\console\Application.php(794): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 C:\xampp\htdocs\todolist\vendor\symfony\console\Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Foundation\Console\ModelMakeCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 C:\xampp\htdocs\todolist\vendor\symfony\console\Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 C:\xampp\htdocs\todolist\artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 {main}  
[2019-09-22 19:35:34] local.ERROR: PDOException: could not find driver in C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php:55
Stack trace:
#0 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php(55): PDO->__construct('mysql:host=127....', 'root', '', Array)
#1 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Database\Connectors\MySqlConnector.php(24): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=127....', Array, Array)
#2 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Database\Connectors\ConnectionFactory.php(61): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
#3 [internal function]: Illuminate\Database\Connectors\ConnectionFactory->Illuminate\Database\Connectors\{closure}()
#4 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Database\Connection.php(924): call_user_func(Object(Closure))
#5 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Database\Connection.php(792): Illuminate\Database\Connection->getPdo()
#6 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Database\Connection.php(677): Illuminate\Database\Connection->reconnectIfMissingConnection()
#7 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Database\Connection.php(349): Illuminate\Database\Connection->run('select * from i...', Array, Object(Closure))
#8 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Database\Schema\MySqlBuilder.php(21): Illuminate\Database\Connection->select('select * from i...', Array)
#9 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Database\Migrations\DatabaseMigrationRepository.php(141): Illuminate\Database\Schema\MySqlBuilder->hasTable('migrations')
#10 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php(404): Illuminate\Database\Migrations\DatabaseMigrationRepository->repositoryExists()
#11 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Database\Console\Migrations\MigrateCommand.php(103): Illuminate\Database\Migrations\Migrator->repositoryExists()
#12 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Database\Console\Migrations\MigrateCommand.php(58): Illuminate\Database\Console\Migrations\MigrateCommand->prepareDatabase()
#13 [internal function]: Illuminate\Database\Console\Migrations\MigrateCommand->fire()
#14 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Container\Container.php(507): call_user_func_array(Array, Array)
#15 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Console\Command.php(169): Illuminate\Container\Container->call(Array)
#16 C:\xampp\htdocs\todolist\vendor\symfony\console\Command\Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Console\Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 C:\xampp\htdocs\todolist\vendor\symfony\console\Application.php(794): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 C:\xampp\htdocs\todolist\vendor\symfony\console\Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Database\Console\Migrations\MigrateCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 C:\xampp\htdocs\todolist\vendor\symfony\console\Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 C:\xampp\htdocs\todolist\artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 {main}  
[2019-09-22 19:36:12] local.ERROR: PDOException: could not find driver in C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php:55
Stack trace:
#0 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php(55): PDO->__construct('mysql:host=127....', 'root', NULL, Array)
#1 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Database\Connectors\MySqlConnector.php(24): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=127....', Array, Array)
#2 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Database\Connectors\ConnectionFactory.php(61): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
#3 [internal function]: Illuminate\Database\Connectors\ConnectionFactory->Illuminate\Database\Connectors\{closure}()
#4 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Database\Connection.php(924): call_user_func(Object(Closure))
#5 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Database\Connection.php(792): Illuminate\Database\Connection->getPdo()
#6 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Database\Connection.php(677): Illuminate\Database\Connection->reconnectIfMissingConnection()
#7 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Database\Connection.php(349): Illuminate\Database\Connection->run('select * from i...', Array, Object(Closure))
#8 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Database\Schema\MySqlBuilder.php(21): Illuminate\Database\Connection->select('select * from i...', Array)
#9 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Database\Migrations\DatabaseMigrationRepository.php(141): Illuminate\Database\Schema\MySqlBuilder->hasTable('migrations')
#10 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php(404): Illuminate\Database\Migrations\DatabaseMigrationRepository->repositoryExists()
#11 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Database\Console\Migrations\MigrateCommand.php(103): Illuminate\Database\Migrations\Migrator->repositoryExists()
#12 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Database\Console\Migrations\MigrateCommand.php(58): Illuminate\Database\Console\Migrations\MigrateCommand->prepareDatabase()
#13 [internal function]: Illuminate\Database\Console\Migrations\MigrateCommand->fire()
#14 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Container\Container.php(507): call_user_func_array(Array, Array)
#15 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Console\Command.php(169): Illuminate\Container\Container->call(Array)
#16 C:\xampp\htdocs\todolist\vendor\symfony\console\Command\Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Console\Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 C:\xampp\htdocs\todolist\vendor\symfony\console\Application.php(794): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 C:\xampp\htdocs\todolist\vendor\symfony\console\Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Database\Console\Migrations\MigrateCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 C:\xampp\htdocs\todolist\vendor\symfony\console\Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 C:\xampp\htdocs\todolist\artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 {main}  
[2019-09-22 19:45:07] local.ERROR: PDOException: could not find driver in C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php:55
Stack trace:
#0 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php(55): PDO->__construct('mysql:host=127....', 'root', NULL, Array)
#1 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Database\Connectors\MySqlConnector.php(24): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=127....', Array, Array)
#2 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Database\Connectors\ConnectionFactory.php(61): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
#3 [internal function]: Illuminate\Database\Connectors\ConnectionFactory->Illuminate\Database\Connectors\{closure}()
#4 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Database\Connection.php(924): call_user_func(Object(Closure))
#5 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Database\Connection.php(792): Illuminate\Database\Connection->getPdo()
#6 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Database\Connection.php(677): Illuminate\Database\Connection->reconnectIfMissingConnection()
#7 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Database\Connection.php(349): Illuminate\Database\Connection->run('select * from i...', Array, Object(Closure))
#8 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Database\Schema\MySqlBuilder.php(21): Illuminate\Database\Connection->select('select * from i...', Array)
#9 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Database\Migrations\DatabaseMigrationRepository.php(141): Illuminate\Database\Schema\MySqlBuilder->hasTable('migrations')
#10 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php(404): Illuminate\Database\Migrations\DatabaseMigrationRepository->repositoryExists()
#11 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Database\Console\Migrations\MigrateCommand.php(103): Illuminate\Database\Migrations\Migrator->repositoryExists()
#12 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Database\Console\Migrations\MigrateCommand.php(58): Illuminate\Database\Console\Migrations\MigrateCommand->prepareDatabase()
#13 [internal function]: Illuminate\Database\Console\Migrations\MigrateCommand->fire()
#14 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Container\Container.php(507): call_user_func_array(Array, Array)
#15 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Console\Command.php(169): Illuminate\Container\Container->call(Array)
#16 C:\xampp\htdocs\todolist\vendor\symfony\console\Command\Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Console\Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 C:\xampp\htdocs\todolist\vendor\symfony\console\Application.php(794): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 C:\xampp\htdocs\todolist\vendor\symfony\console\Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Database\Console\Migrations\MigrateCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 C:\xampp\htdocs\todolist\vendor\symfony\console\Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 C:\xampp\htdocs\todolist\artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 {main}  
[2019-09-22 19:50:30] local.ERROR: PDOException: could not find driver in C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php:55
Stack trace:
#0 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php(55): PDO->__construct('mysql:host=127....', 'root', NULL, Array)
#1 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Database\Connectors\MySqlConnector.php(24): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=127....', Array, Array)
#2 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Database\Connectors\ConnectionFactory.php(61): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
#3 [internal function]: Illuminate\Database\Connectors\ConnectionFactory->Illuminate\Database\Connectors\{closure}()
#4 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Database\Connection.php(924): call_user_func(Object(Closure))
#5 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Database\Connection.php(792): Illuminate\Database\Connection->getPdo()
#6 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Database\Connection.php(677): Illuminate\Database\Connection->reconnectIfMissingConnection()
#7 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Database\Connection.php(349): Illuminate\Database\Connection->run('select * from i...', Array, Object(Closure))
#8 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Database\Schema\MySqlBuilder.php(21): Illuminate\Database\Connection->select('select * from i...', Array)
#9 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Database\Migrations\DatabaseMigrationRepository.php(141): Illuminate\Database\Schema\MySqlBuilder->hasTable('migrations')
#10 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php(404): Illuminate\Database\Migrations\DatabaseMigrationRepository->repositoryExists()
#11 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Database\Console\Migrations\MigrateCommand.php(103): Illuminate\Database\Migrations\Migrator->repositoryExists()
#12 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Database\Console\Migrations\MigrateCommand.php(58): Illuminate\Database\Console\Migrations\MigrateCommand->prepareDatabase()
#13 [internal function]: Illuminate\Database\Console\Migrations\MigrateCommand->fire()
#14 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Container\Container.php(507): call_user_func_array(Array, Array)
#15 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Console\Command.php(169): Illuminate\Container\Container->call(Array)
#16 C:\xampp\htdocs\todolist\vendor\symfony\console\Command\Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Console\Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 C:\xampp\htdocs\todolist\vendor\symfony\console\Application.php(794): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 C:\xampp\htdocs\todolist\vendor\symfony\console\Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Database\Console\Migrations\MigrateCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 C:\xampp\htdocs\todolist\vendor\symfony\console\Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 C:\xampp\htdocs\todolist\artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 {main}  
[2019-09-23 03:19:38] local.ERROR: exception 'BadMethodCallException' with message 'Method prefix does not exist.' in C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Support\Traits\Macroable.php:74
Stack trace:
#0 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(217): Illuminate\Routing\Router->__call('prefix', Array)
#1 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(217): Illuminate\Routing\Router->prefix('api')
#2 C:\xampp\htdocs\todolist\app\Http\routes.php(18): Illuminate\Support\Facades\Facade::__callStatic('prefix', Array)
#3 C:\xampp\htdocs\todolist\app\Http\routes.php(18): Illuminate\Support\Facades\Route::prefix('api')
#4 C:\xampp\htdocs\todolist\app\Providers\RouteServiceProvider.php(58): require('C:\\xampp\\htdocs...')
#5 [internal function]: App\Providers\RouteServiceProvider->App\Providers\{closure}(Object(Illuminate\Routing\Router))
#6 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Routing\Router.php(398): call_user_func(Object(Closure), Object(Illuminate\Routing\Router))
#7 C:\xampp\htdocs\todolist\app\Providers\RouteServiceProvider.php(59): Illuminate\Routing\Router->group(Array, Object(Closure))
#8 C:\xampp\htdocs\todolist\app\Providers\RouteServiceProvider.php(40): App\Providers\RouteServiceProvider->mapWebRoutes(Object(Illuminate\Routing\Router))
#9 [internal function]: App\Providers\RouteServiceProvider->map(Object(Illuminate\Routing\Router))
#10 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Container\Container.php(507): call_user_func_array(Array, Array)
#11 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Support\Providers\RouteServiceProvider.php(72): Illuminate\Container\Container->call(Array)
#12 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Support\Providers\RouteServiceProvider.php(31): Illuminate\Foundation\Support\Providers\RouteServiceProvider->loadRoutes()
#13 C:\xampp\htdocs\todolist\app\Providers\RouteServiceProvider.php(29): Illuminate\Foundation\Support\Providers\RouteServiceProvider->boot(Object(Illuminate\Routing\Router))
#14 [internal function]: App\Providers\RouteServiceProvider->boot(Object(Illuminate\Routing\Router))
#15 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Container\Container.php(507): call_user_func_array(Array, Array)
#16 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(757): Illuminate\Container\Container->call(Array)
#17 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(740): Illuminate\Foundation\Application->bootProvider(Object(App\Providers\RouteServiceProvider))
#18 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(App\Providers\RouteServiceProvider), 14)
#19 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(741): array_walk(Array, Object(Closure))
#20 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\BootProviders.php(17): Illuminate\Foundation\Application->boot()
#21 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(203): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#22 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(219): Illuminate\Foundation\Application->bootstrapWith(Array)
#23 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(105): Illuminate\Foundation\Console\Kernel->bootstrap()
#24 C:\xampp\htdocs\todolist\artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 {main}  
[2019-09-23 03:21:14] local.ERROR: exception 'BadMethodCallException' with message 'Method prefix does not exist.' in C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Support\Traits\Macroable.php:74
Stack trace:
#0 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(217): Illuminate\Routing\Router->__call('prefix', Array)
#1 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(217): Illuminate\Routing\Router->prefix('api')
#2 C:\xampp\htdocs\todolist\app\Http\routes.php(18): Illuminate\Support\Facades\Facade::__callStatic('prefix', Array)
#3 C:\xampp\htdocs\todolist\app\Http\routes.php(18): Illuminate\Support\Facades\Route::prefix('api')
#4 C:\xampp\htdocs\todolist\app\Providers\RouteServiceProvider.php(58): require('C:\\xampp\\htdocs...')
#5 [internal function]: App\Providers\RouteServiceProvider->App\Providers\{closure}(Object(Illuminate\Routing\Router))
#6 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Routing\Router.php(398): call_user_func(Object(Closure), Object(Illuminate\Routing\Router))
#7 C:\xampp\htdocs\todolist\app\Providers\RouteServiceProvider.php(59): Illuminate\Routing\Router->group(Array, Object(Closure))
#8 C:\xampp\htdocs\todolist\app\Providers\RouteServiceProvider.php(40): App\Providers\RouteServiceProvider->mapWebRoutes(Object(Illuminate\Routing\Router))
#9 [internal function]: App\Providers\RouteServiceProvider->map(Object(Illuminate\Routing\Router))
#10 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Container\Container.php(507): call_user_func_array(Array, Array)
#11 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Support\Providers\RouteServiceProvider.php(72): Illuminate\Container\Container->call(Array)
#12 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Support\Providers\RouteServiceProvider.php(31): Illuminate\Foundation\Support\Providers\RouteServiceProvider->loadRoutes()
#13 C:\xampp\htdocs\todolist\app\Providers\RouteServiceProvider.php(29): Illuminate\Foundation\Support\Providers\RouteServiceProvider->boot(Object(Illuminate\Routing\Router))
#14 [internal function]: App\Providers\RouteServiceProvider->boot(Object(Illuminate\Routing\Router))
#15 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Container\Container.php(507): call_user_func_array(Array, Array)
#16 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(757): Illuminate\Container\Container->call(Array)
#17 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(740): Illuminate\Foundation\Application->bootProvider(Object(App\Providers\RouteServiceProvider))
#18 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(App\Providers\RouteServiceProvider), 14)
#19 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(741): array_walk(Array, Object(Closure))
#20 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\BootProviders.php(17): Illuminate\Foundation\Application->boot()
#21 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(203): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#22 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(219): Illuminate\Foundation\Application->bootstrapWith(Array)
#23 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(105): Illuminate\Foundation\Console\Kernel->bootstrap()
#24 C:\xampp\htdocs\todolist\artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 {main}  
[2019-09-23 03:21:26] local.ERROR: exception 'BadMethodCallException' with message 'Method prefix does not exist.' in C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Support\Traits\Macroable.php:74
Stack trace:
#0 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(217): Illuminate\Routing\Router->__call('prefix', Array)
#1 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(217): Illuminate\Routing\Router->prefix('api')
#2 C:\xampp\htdocs\todolist\app\Http\routes.php(18): Illuminate\Support\Facades\Facade::__callStatic('prefix', Array)
#3 C:\xampp\htdocs\todolist\app\Http\routes.php(18): Illuminate\Support\Facades\Route::prefix('api')
#4 C:\xampp\htdocs\todolist\app\Providers\RouteServiceProvider.php(58): require('C:\\xampp\\htdocs...')
#5 [internal function]: App\Providers\RouteServiceProvider->App\Providers\{closure}(Object(Illuminate\Routing\Router))
#6 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Routing\Router.php(398): call_user_func(Object(Closure), Object(Illuminate\Routing\Router))
#7 C:\xampp\htdocs\todolist\app\Providers\RouteServiceProvider.php(59): Illuminate\Routing\Router->group(Array, Object(Closure))
#8 C:\xampp\htdocs\todolist\app\Providers\RouteServiceProvider.php(40): App\Providers\RouteServiceProvider->mapWebRoutes(Object(Illuminate\Routing\Router))
#9 [internal function]: App\Providers\RouteServiceProvider->map(Object(Illuminate\Routing\Router))
#10 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Container\Container.php(507): call_user_func_array(Array, Array)
#11 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Support\Providers\RouteServiceProvider.php(72): Illuminate\Container\Container->call(Array)
#12 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Support\Providers\RouteServiceProvider.php(31): Illuminate\Foundation\Support\Providers\RouteServiceProvider->loadRoutes()
#13 C:\xampp\htdocs\todolist\app\Providers\RouteServiceProvider.php(29): Illuminate\Foundation\Support\Providers\RouteServiceProvider->boot(Object(Illuminate\Routing\Router))
#14 [internal function]: App\Providers\RouteServiceProvider->boot(Object(Illuminate\Routing\Router))
#15 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Container\Container.php(507): call_user_func_array(Array, Array)
#16 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(757): Illuminate\Container\Container->call(Array)
#17 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(740): Illuminate\Foundation\Application->bootProvider(Object(App\Providers\RouteServiceProvider))
#18 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(App\Providers\RouteServiceProvider), 14)
#19 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(741): array_walk(Array, Object(Closure))
#20 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\BootProviders.php(17): Illuminate\Foundation\Application->boot()
#21 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(203): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#22 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(219): Illuminate\Foundation\Application->bootstrapWith(Array)
#23 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(105): Illuminate\Foundation\Console\Kernel->bootstrap()
#24 C:\xampp\htdocs\todolist\artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 {main}  
[2019-09-23 03:22:26] local.ERROR: exception 'BadMethodCallException' with message 'Method prefix does not exist.' in C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Support\Traits\Macroable.php:74
Stack trace:
#0 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(217): Illuminate\Routing\Router->__call('prefix', Array)
#1 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(217): Illuminate\Routing\Router->prefix('api')
#2 C:\xampp\htdocs\todolist\app\Http\routes.php(18): Illuminate\Support\Facades\Facade::__callStatic('prefix', Array)
#3 C:\xampp\htdocs\todolist\app\Http\routes.php(18): Illuminate\Support\Facades\Route::prefix('api')
#4 C:\xampp\htdocs\todolist\app\Providers\RouteServiceProvider.php(58): require('C:\\xampp\\htdocs...')
#5 [internal function]: App\Providers\RouteServiceProvider->App\Providers\{closure}(Object(Illuminate\Routing\Router))
#6 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Routing\Router.php(398): call_user_func(Object(Closure), Object(Illuminate\Routing\Router))
#7 C:\xampp\htdocs\todolist\app\Providers\RouteServiceProvider.php(59): Illuminate\Routing\Router->group(Array, Object(Closure))
#8 C:\xampp\htdocs\todolist\app\Providers\RouteServiceProvider.php(40): App\Providers\RouteServiceProvider->mapWebRoutes(Object(Illuminate\Routing\Router))
#9 [internal function]: App\Providers\RouteServiceProvider->map(Object(Illuminate\Routing\Router))
#10 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Container\Container.php(507): call_user_func_array(Array, Array)
#11 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Support\Providers\RouteServiceProvider.php(72): Illuminate\Container\Container->call(Array)
#12 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Support\Providers\RouteServiceProvider.php(31): Illuminate\Foundation\Support\Providers\RouteServiceProvider->loadRoutes()
#13 C:\xampp\htdocs\todolist\app\Providers\RouteServiceProvider.php(29): Illuminate\Foundation\Support\Providers\RouteServiceProvider->boot(Object(Illuminate\Routing\Router))
#14 [internal function]: App\Providers\RouteServiceProvider->boot(Object(Illuminate\Routing\Router))
#15 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Container\Container.php(507): call_user_func_array(Array, Array)
#16 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(757): Illuminate\Container\Container->call(Array)
#17 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(740): Illuminate\Foundation\Application->bootProvider(Object(App\Providers\RouteServiceProvider))
#18 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(App\Providers\RouteServiceProvider), 14)
#19 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(741): array_walk(Array, Object(Closure))
#20 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\BootProviders.php(17): Illuminate\Foundation\Application->boot()
#21 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(203): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#22 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(219): Illuminate\Foundation\Application->bootstrapWith(Array)
#23 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(105): Illuminate\Foundation\Console\Kernel->bootstrap()
#24 C:\xampp\htdocs\todolist\artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 {main}  
[2019-09-23 03:22:49] local.ERROR: exception 'BadMethodCallException' with message 'Method prefix does not exist.' in C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Support\Traits\Macroable.php:74
Stack trace:
#0 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(217): Illuminate\Routing\Router->__call('prefix', Array)
#1 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(217): Illuminate\Routing\Router->prefix('api')
#2 C:\xampp\htdocs\todolist\app\Http\routes.php(18): Illuminate\Support\Facades\Facade::__callStatic('prefix', Array)
#3 C:\xampp\htdocs\todolist\app\Http\routes.php(18): Illuminate\Support\Facades\Route::prefix('api')
#4 C:\xampp\htdocs\todolist\app\Providers\RouteServiceProvider.php(58): require('C:\\xampp\\htdocs...')
#5 [internal function]: App\Providers\RouteServiceProvider->App\Providers\{closure}(Object(Illuminate\Routing\Router))
#6 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Routing\Router.php(398): call_user_func(Object(Closure), Object(Illuminate\Routing\Router))
#7 C:\xampp\htdocs\todolist\app\Providers\RouteServiceProvider.php(59): Illuminate\Routing\Router->group(Array, Object(Closure))
#8 C:\xampp\htdocs\todolist\app\Providers\RouteServiceProvider.php(40): App\Providers\RouteServiceProvider->mapWebRoutes(Object(Illuminate\Routing\Router))
#9 [internal function]: App\Providers\RouteServiceProvider->map(Object(Illuminate\Routing\Router))
#10 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Container\Container.php(507): call_user_func_array(Array, Array)
#11 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Support\Providers\RouteServiceProvider.php(72): Illuminate\Container\Container->call(Array)
#12 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Support\Providers\RouteServiceProvider.php(31): Illuminate\Foundation\Support\Providers\RouteServiceProvider->loadRoutes()
#13 C:\xampp\htdocs\todolist\app\Providers\RouteServiceProvider.php(29): Illuminate\Foundation\Support\Providers\RouteServiceProvider->boot(Object(Illuminate\Routing\Router))
#14 [internal function]: App\Providers\RouteServiceProvider->boot(Object(Illuminate\Routing\Router))
#15 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Container\Container.php(507): call_user_func_array(Array, Array)
#16 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(757): Illuminate\Container\Container->call(Array)
#17 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(740): Illuminate\Foundation\Application->bootProvider(Object(App\Providers\RouteServiceProvider))
#18 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(App\Providers\RouteServiceProvider), 14)
#19 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(741): array_walk(Array, Object(Closure))
#20 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\BootProviders.php(17): Illuminate\Foundation\Application->boot()
#21 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(203): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#22 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(219): Illuminate\Foundation\Application->bootstrapWith(Array)
#23 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(105): Illuminate\Foundation\Console\Kernel->bootstrap()
#24 C:\xampp\htdocs\todolist\artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 {main}  
[2019-09-23 03:30:41] local.ERROR: exception 'BadMethodCallException' with message 'Method prefix does not exist.' in C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Support\Traits\Macroable.php:74
Stack trace:
#0 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(217): Illuminate\Routing\Router->__call('prefix', Array)
#1 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(217): Illuminate\Routing\Router->prefix('api')
#2 C:\xampp\htdocs\todolist\app\Http\routes.php(18): Illuminate\Support\Facades\Facade::__callStatic('prefix', Array)
#3 C:\xampp\htdocs\todolist\app\Http\routes.php(18): Illuminate\Support\Facades\Route::prefix('api')
#4 C:\xampp\htdocs\todolist\app\Providers\RouteServiceProvider.php(58): require('C:\\xampp\\htdocs...')
#5 [internal function]: App\Providers\RouteServiceProvider->App\Providers\{closure}(Object(Illuminate\Routing\Router))
#6 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Routing\Router.php(398): call_user_func(Object(Closure), Object(Illuminate\Routing\Router))
#7 C:\xampp\htdocs\todolist\app\Providers\RouteServiceProvider.php(59): Illuminate\Routing\Router->group(Array, Object(Closure))
#8 C:\xampp\htdocs\todolist\app\Providers\RouteServiceProvider.php(40): App\Providers\RouteServiceProvider->mapWebRoutes(Object(Illuminate\Routing\Router))
#9 [internal function]: App\Providers\RouteServiceProvider->map(Object(Illuminate\Routing\Router))
#10 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Container\Container.php(507): call_user_func_array(Array, Array)
#11 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Support\Providers\RouteServiceProvider.php(72): Illuminate\Container\Container->call(Array)
#12 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Support\Providers\RouteServiceProvider.php(31): Illuminate\Foundation\Support\Providers\RouteServiceProvider->loadRoutes()
#13 C:\xampp\htdocs\todolist\app\Providers\RouteServiceProvider.php(29): Illuminate\Foundation\Support\Providers\RouteServiceProvider->boot(Object(Illuminate\Routing\Router))
#14 [internal function]: App\Providers\RouteServiceProvider->boot(Object(Illuminate\Routing\Router))
#15 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Container\Container.php(507): call_user_func_array(Array, Array)
#16 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(757): Illuminate\Container\Container->call(Array)
#17 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(740): Illuminate\Foundation\Application->bootProvider(Object(App\Providers\RouteServiceProvider))
#18 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(App\Providers\RouteServiceProvider), 14)
#19 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(741): array_walk(Array, Object(Closure))
#20 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\BootProviders.php(17): Illuminate\Foundation\Application->boot()
#21 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(203): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#22 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(219): Illuminate\Foundation\Application->bootstrapWith(Array)
#23 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(105): Illuminate\Foundation\Console\Kernel->bootstrap()
#24 C:\xampp\htdocs\todolist\artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 {main}  
[2019-09-23 08:57:04] local.ERROR: exception 'Symfony\Component\Console\Exception\CommandNotFoundException' with message 'Command "server" is not defined.

Did you mean this?
    serve' in C:\xampp\htdocs\todolist\vendor\symfony\console\Application.php:515
Stack trace:
#0 C:\xampp\htdocs\todolist\vendor\symfony\console\Application.php(183): Symfony\Component\Console\Application->find('server')
#1 C:\xampp\htdocs\todolist\vendor\symfony\console\Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 C:\xampp\htdocs\todolist\artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 {main}  
[2019-09-23 09:21:10] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 09:21:41] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 09:25:20] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 09:26:28] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 09:50:27] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 09:50:30] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 09:58:50] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 09:58:52] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 09:59:12] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 09:59:16] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 09:59:46] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:02:18] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:03:10] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:03:24] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:03:27] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:03:28] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:03:28] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:03:29] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:03:29] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:03:31] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:03:31] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:03:31] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:03:31] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:03:33] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:03:37] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:03:39] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:03:39] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:04:05] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:04:25] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:04:50] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:04:57] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:04:57] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:04:57] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:04:58] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:14:02] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:14:05] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:14:05] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:14:06] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:14:06] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:14:07] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:14:07] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:14:07] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:14:08] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:14:08] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:14:08] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:14:08] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:14:11] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:14:11] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:14:11] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:14:12] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:14:12] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:15:30] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:15:32] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:15:32] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:15:35] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:15:35] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:15:35] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:15:36] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:15:36] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:17:13] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:17:17] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:17:23] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:17:24] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:17:24] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:17:24] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:17:24] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:17:25] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:17:25] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:17:25] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:17:25] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:17:26] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:17:26] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:17:26] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:25:34] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:25:53] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:27:51] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:39:59] local.ERROR: exception 'ErrorException' with message 'Missing argument 2 for Illuminate\Routing\Router::middleware(), called in C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php on line 217 and defined' in C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Routing\Router.php:916
Stack trace:
#0 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Routing\Router.php(916): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Missing argumen...', 'C:\\xampp\\htdocs...', 916, Array)
#1 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(217): Illuminate\Routing\Router->middleware('auth:api')
#2 C:\xampp\htdocs\todolist\app\Http\api-routes.php(22): Illuminate\Support\Facades\Facade::__callStatic('middleware', Array)
#3 C:\xampp\htdocs\todolist\app\Http\api-routes.php(22): Illuminate\Support\Facades\Route::middleware('auth:api')
#4 C:\xampp\htdocs\todolist\app\Providers\RouteServiceProvider.php(68): require('C:\\xampp\\htdocs...')
#5 [internal function]: App\Providers\RouteServiceProvider->App\Providers\{closure}(Object(Illuminate\Routing\Router))
#6 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Routing\Router.php(398): call_user_func(Object(Closure), Object(Illuminate\Routing\Router))
#7 C:\xampp\htdocs\todolist\app\Providers\RouteServiceProvider.php(69): Illuminate\Routing\Router->group(Array, Object(Closure))
#8 C:\xampp\htdocs\todolist\app\Providers\RouteServiceProvider.php(43): App\Providers\RouteServiceProvider->mapApiRoutes(Object(Illuminate\Routing\Router))
#9 [internal function]: App\Providers\RouteServiceProvider->map(Object(Illuminate\Routing\Router))
#10 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Container\Container.php(507): call_user_func_array(Array, Array)
#11 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Support\Providers\RouteServiceProvider.php(72): Illuminate\Container\Container->call(Array)
#12 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Support\Providers\RouteServiceProvider.php(31): Illuminate\Foundation\Support\Providers\RouteServiceProvider->loadRoutes()
#13 C:\xampp\htdocs\todolist\app\Providers\RouteServiceProvider.php(29): Illuminate\Foundation\Support\Providers\RouteServiceProvider->boot(Object(Illuminate\Routing\Router))
#14 [internal function]: App\Providers\RouteServiceProvider->boot(Object(Illuminate\Routing\Router))
#15 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Container\Container.php(507): call_user_func_array(Array, Array)
#16 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(757): Illuminate\Container\Container->call(Array)
#17 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(740): Illuminate\Foundation\Application->bootProvider(Object(App\Providers\RouteServiceProvider))
#18 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(App\Providers\RouteServiceProvider), 14)
#19 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(741): array_walk(Array, Object(Closure))
#20 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\BootProviders.php(17): Illuminate\Foundation\Application->boot()
#21 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(203): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#22 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(232): Illuminate\Foundation\Application->bootstrapWith(Array)
#23 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(127): Illuminate\Foundation\Http\Kernel->bootstrap()
#24 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(99): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#25 C:\xampp\htdocs\todolist\public\index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#26 C:\xampp\htdocs\todolist\server.php(21): require_once('C:\\xampp\\htdocs...')
#27 {main}  
[2019-09-23 10:40:09] local.ERROR: exception 'ErrorException' with message 'Missing argument 2 for Illuminate\Routing\Router::middleware(), called in C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php on line 217 and defined' in C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Routing\Router.php:916
Stack trace:
#0 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Routing\Router.php(916): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Missing argumen...', 'C:\\xampp\\htdocs...', 916, Array)
#1 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(217): Illuminate\Routing\Router->middleware('auth:api')
#2 C:\xampp\htdocs\todolist\app\Http\api-routes.php(22): Illuminate\Support\Facades\Facade::__callStatic('middleware', Array)
#3 C:\xampp\htdocs\todolist\app\Http\api-routes.php(22): Illuminate\Support\Facades\Route::middleware('auth:api')
#4 C:\xampp\htdocs\todolist\app\Providers\RouteServiceProvider.php(68): require('C:\\xampp\\htdocs...')
#5 [internal function]: App\Providers\RouteServiceProvider->App\Providers\{closure}(Object(Illuminate\Routing\Router))
#6 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Routing\Router.php(398): call_user_func(Object(Closure), Object(Illuminate\Routing\Router))
#7 C:\xampp\htdocs\todolist\app\Providers\RouteServiceProvider.php(69): Illuminate\Routing\Router->group(Array, Object(Closure))
#8 C:\xampp\htdocs\todolist\app\Providers\RouteServiceProvider.php(43): App\Providers\RouteServiceProvider->mapApiRoutes(Object(Illuminate\Routing\Router))
#9 [internal function]: App\Providers\RouteServiceProvider->map(Object(Illuminate\Routing\Router))
#10 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Container\Container.php(507): call_user_func_array(Array, Array)
#11 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Support\Providers\RouteServiceProvider.php(72): Illuminate\Container\Container->call(Array)
#12 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Support\Providers\RouteServiceProvider.php(31): Illuminate\Foundation\Support\Providers\RouteServiceProvider->loadRoutes()
#13 C:\xampp\htdocs\todolist\app\Providers\RouteServiceProvider.php(29): Illuminate\Foundation\Support\Providers\RouteServiceProvider->boot(Object(Illuminate\Routing\Router))
#14 [internal function]: App\Providers\RouteServiceProvider->boot(Object(Illuminate\Routing\Router))
#15 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Container\Container.php(507): call_user_func_array(Array, Array)
#16 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(757): Illuminate\Container\Container->call(Array)
#17 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(740): Illuminate\Foundation\Application->bootProvider(Object(App\Providers\RouteServiceProvider))
#18 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(App\Providers\RouteServiceProvider), 14)
#19 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(741): array_walk(Array, Object(Closure))
#20 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\BootProviders.php(17): Illuminate\Foundation\Application->boot()
#21 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(203): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#22 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(232): Illuminate\Foundation\Application->bootstrapWith(Array)
#23 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(127): Illuminate\Foundation\Http\Kernel->bootstrap()
#24 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(99): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#25 C:\xampp\htdocs\todolist\public\index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#26 C:\xampp\htdocs\todolist\server.php(21): require_once('C:\\xampp\\htdocs...')
#27 {main}  
[2019-09-23 10:40:33] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:40:42] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:41:28] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:41:32] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:41:33] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:45:22] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Repositories\Repository' not found' in C:\xampp\htdocs\todolist\app\Http\Controllers\TaskController.php:13
Stack trace:
#0 {main}  
[2019-09-23 10:45:43] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Repositories\Repository' not found' in C:\xampp\htdocs\todolist\app\Http\Controllers\TaskController.php:13
Stack trace:
#0 {main}  
[2019-09-23 10:48:39] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:48:43] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:52:56] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:53:02] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:53:13] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:53:43] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:53:46] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:53:50] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:53:54] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:54:01] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:54:16] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:54:20] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:54:23] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:56:04] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:56:21] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:56:34] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 10:59:30] local.ERROR: exception 'ReflectionException' with message 'Class App\Http\Controllers\Api\TaskController does not exist' in C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Container\Container.php:734
Stack trace:
#0 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Container\Container.php(734): ReflectionClass->__construct('App\\Http\\Contro...')
#1 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Container\Container.php(629): Illuminate\Container\Container->build('App\\Http\\Contro...', Array)
#2 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(697): Illuminate\Container\Container->make('App\\Http\\Contro...', Array)
#3 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Console\RouteListCommand.php(165): Illuminate\Foundation\Application->make('App\\Http\\Contro...')
#4 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Console\RouteListCommand.php(146): Illuminate\Foundation\Console\RouteListCommand->getControllerMiddleware('App\\Http\\Contro...')
#5 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Console\RouteListCommand.php(118): Illuminate\Foundation\Console\RouteListCommand->getMiddleware(Object(Illuminate\Routing\Route))
#6 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Console\RouteListCommand.php(88): Illuminate\Foundation\Console\RouteListCommand->getRouteInformation(Object(Illuminate\Routing\Route))
#7 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Console\RouteListCommand.php(75): Illuminate\Foundation\Console\RouteListCommand->getRoutes()
#8 [internal function]: Illuminate\Foundation\Console\RouteListCommand->fire()
#9 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Container\Container.php(507): call_user_func_array(Array, Array)
#10 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Console\Command.php(169): Illuminate\Container\Container->call(Array)
#11 C:\xampp\htdocs\todolist\vendor\symfony\console\Command\Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Console\Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 C:\xampp\htdocs\todolist\vendor\symfony\console\Application.php(794): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 C:\xampp\htdocs\todolist\vendor\symfony\console\Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Foundation\Console\RouteListCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 C:\xampp\htdocs\todolist\vendor\symfony\console\Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 C:\xampp\htdocs\todolist\artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 {main}  
[2019-09-23 10:59:57] local.ERROR: exception 'ReflectionException' with message 'Class App\Http\Controllers\Api\TaskController does not exist' in C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Container\Container.php:734
Stack trace:
#0 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Container\Container.php(734): ReflectionClass->__construct('App\\Http\\Contro...')
#1 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Container\Container.php(629): Illuminate\Container\Container->build('App\\Http\\Contro...', Array)
#2 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(697): Illuminate\Container\Container->make('App\\Http\\Contro...', Array)
#3 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Console\RouteListCommand.php(165): Illuminate\Foundation\Application->make('App\\Http\\Contro...')
#4 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Console\RouteListCommand.php(146): Illuminate\Foundation\Console\RouteListCommand->getControllerMiddleware('App\\Http\\Contro...')
#5 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Console\RouteListCommand.php(118): Illuminate\Foundation\Console\RouteListCommand->getMiddleware(Object(Illuminate\Routing\Route))
#6 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Console\RouteListCommand.php(88): Illuminate\Foundation\Console\RouteListCommand->getRouteInformation(Object(Illuminate\Routing\Route))
#7 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Console\RouteListCommand.php(75): Illuminate\Foundation\Console\RouteListCommand->getRoutes()
#8 [internal function]: Illuminate\Foundation\Console\RouteListCommand->fire()
#9 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Container\Container.php(507): call_user_func_array(Array, Array)
#10 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Console\Command.php(169): Illuminate\Container\Container->call(Array)
#11 C:\xampp\htdocs\todolist\vendor\symfony\console\Command\Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Console\Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 C:\xampp\htdocs\todolist\vendor\symfony\console\Application.php(794): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 C:\xampp\htdocs\todolist\vendor\symfony\console\Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Foundation\Console\RouteListCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 C:\xampp\htdocs\todolist\vendor\symfony\console\Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 C:\xampp\htdocs\todolist\artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 {main}  
[2019-09-23 11:00:03] local.ERROR: exception 'ReflectionException' with message 'Class App\Http\Controllers\Api\TaskController does not exist' in C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Container\Container.php:734
Stack trace:
#0 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Container\Container.php(734): ReflectionClass->__construct('App\\Http\\Contro...')
#1 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Container\Container.php(629): Illuminate\Container\Container->build('App\\Http\\Contro...', Array)
#2 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(697): Illuminate\Container\Container->make('App\\Http\\Contro...', Array)
#3 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Console\RouteListCommand.php(165): Illuminate\Foundation\Application->make('App\\Http\\Contro...')
#4 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Console\RouteListCommand.php(146): Illuminate\Foundation\Console\RouteListCommand->getControllerMiddleware('App\\Http\\Contro...')
#5 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Console\RouteListCommand.php(118): Illuminate\Foundation\Console\RouteListCommand->getMiddleware(Object(Illuminate\Routing\Route))
#6 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Console\RouteListCommand.php(88): Illuminate\Foundation\Console\RouteListCommand->getRouteInformation(Object(Illuminate\Routing\Route))
#7 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Console\RouteListCommand.php(75): Illuminate\Foundation\Console\RouteListCommand->getRoutes()
#8 [internal function]: Illuminate\Foundation\Console\RouteListCommand->fire()
#9 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Container\Container.php(507): call_user_func_array(Array, Array)
#10 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Console\Command.php(169): Illuminate\Container\Container->call(Array)
#11 C:\xampp\htdocs\todolist\vendor\symfony\console\Command\Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Console\Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 C:\xampp\htdocs\todolist\vendor\symfony\console\Application.php(794): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 C:\xampp\htdocs\todolist\vendor\symfony\console\Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Foundation\Console\RouteListCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 C:\xampp\htdocs\todolist\vendor\symfony\console\Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 C:\xampp\htdocs\todolist\artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 {main}  
[2019-09-23 11:00:37] local.ERROR: exception 'ReflectionException' with message 'Class App\Http\Controllers\Api\TaskController does not exist' in C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Container\Container.php:734
Stack trace:
#0 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Container\Container.php(734): ReflectionClass->__construct('App\\Http\\Contro...')
#1 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Container\Container.php(629): Illuminate\Container\Container->build('App\\Http\\Contro...', Array)
#2 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(697): Illuminate\Container\Container->make('App\\Http\\Contro...', Array)
#3 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Console\RouteListCommand.php(165): Illuminate\Foundation\Application->make('App\\Http\\Contro...')
#4 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Console\RouteListCommand.php(146): Illuminate\Foundation\Console\RouteListCommand->getControllerMiddleware('App\\Http\\Contro...')
#5 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Console\RouteListCommand.php(118): Illuminate\Foundation\Console\RouteListCommand->getMiddleware(Object(Illuminate\Routing\Route))
#6 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Console\RouteListCommand.php(88): Illuminate\Foundation\Console\RouteListCommand->getRouteInformation(Object(Illuminate\Routing\Route))
#7 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Console\RouteListCommand.php(75): Illuminate\Foundation\Console\RouteListCommand->getRoutes()
#8 [internal function]: Illuminate\Foundation\Console\RouteListCommand->fire()
#9 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Container\Container.php(507): call_user_func_array(Array, Array)
#10 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Console\Command.php(169): Illuminate\Container\Container->call(Array)
#11 C:\xampp\htdocs\todolist\vendor\symfony\console\Command\Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Console\Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 C:\xampp\htdocs\todolist\vendor\symfony\console\Application.php(794): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 C:\xampp\htdocs\todolist\vendor\symfony\console\Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Foundation\Console\RouteListCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 C:\xampp\htdocs\todolist\vendor\symfony\console\Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 C:\xampp\htdocs\todolist\artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 {main}  
[2019-09-23 11:01:19] local.ERROR: exception 'BadMethodCallException' with message 'Method mapApiRoutes does not exist.' in C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Support\Traits\Macroable.php:74
Stack trace:
#0 [internal function]: Illuminate\Routing\Router->__call('mapApiRoutes', Array)
#1 [internal function]: Illuminate\Routing\Router->mapApiRoutes(Object(Illuminate\Routing\Router))
#2 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Support\Providers\RouteServiceProvider.php(113): call_user_func_array(Array, Array)
#3 C:\xampp\htdocs\todolist\app\Providers\RouteServiceProvider.php(43): Illuminate\Foundation\Support\Providers\RouteServiceProvider->__call('mapApiRoutes', Array)
#4 C:\xampp\htdocs\todolist\app\Providers\RouteServiceProvider.php(43): App\Providers\RouteServiceProvider->mapApiRoutes(Object(Illuminate\Routing\Router))
#5 [internal function]: App\Providers\RouteServiceProvider->map(Object(Illuminate\Routing\Router))
#6 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Container\Container.php(507): call_user_func_array(Array, Array)
#7 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Support\Providers\RouteServiceProvider.php(72): Illuminate\Container\Container->call(Array)
#8 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Support\Providers\RouteServiceProvider.php(31): Illuminate\Foundation\Support\Providers\RouteServiceProvider->loadRoutes()
#9 C:\xampp\htdocs\todolist\app\Providers\RouteServiceProvider.php(29): Illuminate\Foundation\Support\Providers\RouteServiceProvider->boot(Object(Illuminate\Routing\Router))
#10 [internal function]: App\Providers\RouteServiceProvider->boot(Object(Illuminate\Routing\Router))
#11 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Container\Container.php(507): call_user_func_array(Array, Array)
#12 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(757): Illuminate\Container\Container->call(Array)
#13 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(740): Illuminate\Foundation\Application->bootProvider(Object(App\Providers\RouteServiceProvider))
#14 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(App\Providers\RouteServiceProvider), 14)
#15 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(741): array_walk(Array, Object(Closure))
#16 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\BootProviders.php(17): Illuminate\Foundation\Application->boot()
#17 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(203): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#18 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(219): Illuminate\Foundation\Application->bootstrapWith(Array)
#19 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(105): Illuminate\Foundation\Console\Kernel->bootstrap()
#20 C:\xampp\htdocs\todolist\artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 {main}  
[2019-09-23 11:01:25] local.ERROR: exception 'BadMethodCallException' with message 'Method mapApiRoutes does not exist.' in C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Support\Traits\Macroable.php:74
Stack trace:
#0 [internal function]: Illuminate\Routing\Router->__call('mapApiRoutes', Array)
#1 [internal function]: Illuminate\Routing\Router->mapApiRoutes(Object(Illuminate\Routing\Router))
#2 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Support\Providers\RouteServiceProvider.php(113): call_user_func_array(Array, Array)
#3 C:\xampp\htdocs\todolist\app\Providers\RouteServiceProvider.php(43): Illuminate\Foundation\Support\Providers\RouteServiceProvider->__call('mapApiRoutes', Array)
#4 C:\xampp\htdocs\todolist\app\Providers\RouteServiceProvider.php(43): App\Providers\RouteServiceProvider->mapApiRoutes(Object(Illuminate\Routing\Router))
#5 [internal function]: App\Providers\RouteServiceProvider->map(Object(Illuminate\Routing\Router))
#6 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Container\Container.php(507): call_user_func_array(Array, Array)
#7 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Support\Providers\RouteServiceProvider.php(72): Illuminate\Container\Container->call(Array)
#8 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Support\Providers\RouteServiceProvider.php(31): Illuminate\Foundation\Support\Providers\RouteServiceProvider->loadRoutes()
#9 C:\xampp\htdocs\todolist\app\Providers\RouteServiceProvider.php(29): Illuminate\Foundation\Support\Providers\RouteServiceProvider->boot(Object(Illuminate\Routing\Router))
#10 [internal function]: App\Providers\RouteServiceProvider->boot(Object(Illuminate\Routing\Router))
#11 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Container\Container.php(507): call_user_func_array(Array, Array)
#12 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(757): Illuminate\Container\Container->call(Array)
#13 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(740): Illuminate\Foundation\Application->bootProvider(Object(App\Providers\RouteServiceProvider))
#14 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(App\Providers\RouteServiceProvider), 14)
#15 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(741): array_walk(Array, Object(Closure))
#16 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\BootProviders.php(17): Illuminate\Foundation\Application->boot()
#17 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(203): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#18 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(219): Illuminate\Foundation\Application->bootstrapWith(Array)
#19 C:\xampp\htdocs\todolist\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(105): Illuminate\Foundation\Console\Kernel->bootstrap()
#20 C:\xampp\htdocs\todolist\artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 {main}  
[2019-09-23 11:02:27] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
[2019-09-23 11:02:34] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in C:\xampp\htdocs\todolist\vendor\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php:265
Stack trace:
#0 {main}  
